/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOnboardingRouteImport } from './routes/onboarding/_onboarding'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as OnboardingOnboardingIndexRouteImport } from './routes/onboarding/_onboarding.index'
import { Route as OnboardingOnboardingSubdomainRouteImport } from './routes/onboarding/_onboarding.subdomain'
import { Route as OnboardingOnboardingProRouteImport } from './routes/onboarding/_onboarding.pro'
import { Route as OnboardingOnboardingInvitationsRouteImport } from './routes/onboarding/_onboarding.invitations'
import { Route as AppSlugOrgRouteImport } from './routes/app/$slug/_org'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/_auth.reset-password'
import { Route as authAuthRegisterRouteImport } from './routes/(auth)/_auth.register'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/_auth.forgot-password'
import { Route as AppSlugOrgIndexRouteImport } from './routes/app/$slug/_org.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => OnboardingRoute,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingIndexRoute =
  OnboardingOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OnboardingOnboardingRoute,
  } as any)
const OnboardingOnboardingSubdomainRoute =
  OnboardingOnboardingSubdomainRouteImport.update({
    id: '/subdomain',
    path: '/subdomain',
    getParentRoute: () => OnboardingOnboardingRoute,
  } as any)
const OnboardingOnboardingProRoute = OnboardingOnboardingProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => OnboardingOnboardingRoute,
} as any)
const OnboardingOnboardingInvitationsRoute =
  OnboardingOnboardingInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => OnboardingOnboardingRoute,
  } as any)
const AppSlugOrgRoute = AppSlugOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AppSlugRoute,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authAuthRoute,
} as any)
const AppSlugOrgIndexRoute = AppSlugOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugOrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingOnboardingRouteWithChildren
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/login': typeof authAuthLoginRoute
  '/register': typeof authAuthRegisterRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/app/$slug': typeof AppSlugOrgRouteWithChildren
  '/onboarding/invitations': typeof OnboardingOnboardingInvitationsRoute
  '/onboarding/pro': typeof OnboardingOnboardingProRoute
  '/onboarding/subdomain': typeof OnboardingOnboardingSubdomainRoute
  '/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/app/$slug/': typeof AppSlugOrgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/login': typeof authAuthLoginRoute
  '/register': typeof authAuthRegisterRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/onboarding/invitations': typeof OnboardingOnboardingInvitationsRoute
  '/onboarding/pro': typeof OnboardingOnboardingProRoute
  '/onboarding/subdomain': typeof OnboardingOnboardingSubdomainRoute
  '/onboarding': typeof OnboardingOnboardingIndexRoute
  '/app/$slug': typeof AppSlugOrgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/onboarding/_onboarding': typeof OnboardingOnboardingRouteWithChildren
  '/(auth)/_auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/register': typeof authAuthRegisterRoute
  '/(auth)/_auth/reset-password': typeof authAuthResetPasswordRoute
  '/app/$slug/_org': typeof AppSlugOrgRouteWithChildren
  '/onboarding/_onboarding/invitations': typeof OnboardingOnboardingInvitationsRoute
  '/onboarding/_onboarding/pro': typeof OnboardingOnboardingProRoute
  '/onboarding/_onboarding/subdomain': typeof OnboardingOnboardingSubdomainRoute
  '/onboarding/_onboarding/': typeof OnboardingOnboardingIndexRoute
  '/app/$slug/_org/': typeof AppSlugOrgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$slug'
    | '/onboarding/invitations'
    | '/onboarding/pro'
    | '/onboarding/subdomain'
    | '/onboarding/'
    | '/app/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/onboarding/invitations'
    | '/onboarding/pro'
    | '/onboarding/subdomain'
    | '/onboarding'
    | '/app/$slug'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/onboarding/_onboarding'
    | '/(auth)/_auth/forgot-password'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/register'
    | '/(auth)/_auth/reset-password'
    | '/app/$slug/_org'
    | '/onboarding/_onboarding/invitations'
    | '/onboarding/_onboarding/pro'
    | '/onboarding/_onboarding/subdomain'
    | '/onboarding/_onboarding/'
    | '/app/$slug/_org/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/_onboarding': {
      id: '/onboarding/_onboarding'
      path: ''
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/_onboarding/': {
      id: '/onboarding/_onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingOnboardingIndexRouteImport
      parentRoute: typeof OnboardingOnboardingRoute
    }
    '/onboarding/_onboarding/subdomain': {
      id: '/onboarding/_onboarding/subdomain'
      path: '/subdomain'
      fullPath: '/onboarding/subdomain'
      preLoaderRoute: typeof OnboardingOnboardingSubdomainRouteImport
      parentRoute: typeof OnboardingOnboardingRoute
    }
    '/onboarding/_onboarding/pro': {
      id: '/onboarding/_onboarding/pro'
      path: '/pro'
      fullPath: '/onboarding/pro'
      preLoaderRoute: typeof OnboardingOnboardingProRouteImport
      parentRoute: typeof OnboardingOnboardingRoute
    }
    '/onboarding/_onboarding/invitations': {
      id: '/onboarding/_onboarding/invitations'
      path: '/invitations'
      fullPath: '/onboarding/invitations'
      preLoaderRoute: typeof OnboardingOnboardingInvitationsRouteImport
      parentRoute: typeof OnboardingOnboardingRoute
    }
    '/app/$slug/_org': {
      id: '/app/$slug/_org'
      path: ''
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugOrgRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/(auth)/_auth/reset-password': {
      id: '/(auth)/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/register': {
      id: '/(auth)/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/forgot-password': {
      id: '/(auth)/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/app/$slug/_org/': {
      id: '/app/$slug/_org/'
      path: '/'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AppSlugOrgIndexRouteImport
      parentRoute: typeof AppSlugOrgRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
