/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as ApponboardingOnboardingRouteImport } from './routes/app/(onboarding)/onboarding'
import { Route as authLayoutResetPasswordRouteImport } from './routes/(auth)/_layout.reset-password'
import { Route as authLayoutRegisterRouteImport } from './routes/(auth)/_layout.register'
import { Route as authLayoutLoginRouteImport } from './routes/(auth)/_layout.login'
import { Route as authLayoutForgotPasswordRouteImport } from './routes/(auth)/_layout.forgot-password'
import { Route as ApponboardingOnboardingIndexRouteImport } from './routes/app/(onboarding)/onboarding.index'
import { Route as ApponboardingOnboardingInvitationsRouteImport } from './routes/app/(onboarding)/onboarding.invitations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApponboardingOnboardingRoute = ApponboardingOnboardingRouteImport.update({
  id: '/app/(onboarding)/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutResetPasswordRoute = authLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutRegisterRoute = authLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutLoginRoute = authLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutForgotPasswordRoute =
  authLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authLayoutRoute,
  } as any)
const ApponboardingOnboardingIndexRoute =
  ApponboardingOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ApponboardingOnboardingRoute,
  } as any)
const ApponboardingOnboardingInvitationsRoute =
  ApponboardingOnboardingInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ApponboardingOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authLayoutForgotPasswordRoute
  '/login': typeof authLayoutLoginRoute
  '/register': typeof authLayoutRegisterRoute
  '/reset-password': typeof authLayoutResetPasswordRoute
  '/app/onboarding': typeof ApponboardingOnboardingRouteWithChildren
  '/app/onboarding/invitations': typeof ApponboardingOnboardingInvitationsRoute
  '/app/onboarding/': typeof ApponboardingOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authLayoutForgotPasswordRoute
  '/login': typeof authLayoutLoginRoute
  '/register': typeof authLayoutRegisterRoute
  '/reset-password': typeof authLayoutResetPasswordRoute
  '/app/onboarding/invitations': typeof ApponboardingOnboardingInvitationsRoute
  '/app/onboarding': typeof ApponboardingOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(auth)/_layout/forgot-password': typeof authLayoutForgotPasswordRoute
  '/(auth)/_layout/login': typeof authLayoutLoginRoute
  '/(auth)/_layout/register': typeof authLayoutRegisterRoute
  '/(auth)/_layout/reset-password': typeof authLayoutResetPasswordRoute
  '/app/(onboarding)/onboarding': typeof ApponboardingOnboardingRouteWithChildren
  '/app/(onboarding)/onboarding/invitations': typeof ApponboardingOnboardingInvitationsRoute
  '/app/(onboarding)/onboarding/': typeof ApponboardingOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/onboarding'
    | '/app/onboarding/invitations'
    | '/app/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/onboarding/invitations'
    | '/app/onboarding'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_layout'
    | '/(auth)/_layout/forgot-password'
    | '/(auth)/_layout/login'
    | '/(auth)/_layout/register'
    | '/(auth)/_layout/reset-password'
    | '/app/(onboarding)/onboarding'
    | '/app/(onboarding)/onboarding/invitations'
    | '/app/(onboarding)/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  ApponboardingOnboardingRoute: typeof ApponboardingOnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(onboarding)/onboarding': {
      id: '/app/(onboarding)/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof ApponboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/reset-password': {
      id: '/(auth)/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authLayoutResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/register': {
      id: '/(auth)/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authLayoutRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/login': {
      id: '/(auth)/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLayoutLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/forgot-password': {
      id: '/(auth)/_layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authLayoutForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/app/(onboarding)/onboarding/': {
      id: '/app/(onboarding)/onboarding/'
      path: '/'
      fullPath: '/app/onboarding/'
      preLoaderRoute: typeof ApponboardingOnboardingIndexRouteImport
      parentRoute: typeof ApponboardingOnboardingRoute
    }
    '/app/(onboarding)/onboarding/invitations': {
      id: '/app/(onboarding)/onboarding/invitations'
      path: '/invitations'
      fullPath: '/app/onboarding/invitations'
      preLoaderRoute: typeof ApponboardingOnboardingInvitationsRouteImport
      parentRoute: typeof ApponboardingOnboardingRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutForgotPasswordRoute: typeof authLayoutForgotPasswordRoute
  authLayoutLoginRoute: typeof authLayoutLoginRoute
  authLayoutRegisterRoute: typeof authLayoutRegisterRoute
  authLayoutResetPasswordRoute: typeof authLayoutResetPasswordRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutForgotPasswordRoute: authLayoutForgotPasswordRoute,
  authLayoutLoginRoute: authLayoutLoginRoute,
  authLayoutRegisterRoute: authLayoutRegisterRoute,
  authLayoutResetPasswordRoute: authLayoutResetPasswordRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface ApponboardingOnboardingRouteChildren {
  ApponboardingOnboardingInvitationsRoute: typeof ApponboardingOnboardingInvitationsRoute
  ApponboardingOnboardingIndexRoute: typeof ApponboardingOnboardingIndexRoute
}

const ApponboardingOnboardingRouteChildren: ApponboardingOnboardingRouteChildren =
  {
    ApponboardingOnboardingInvitationsRoute:
      ApponboardingOnboardingInvitationsRoute,
    ApponboardingOnboardingIndexRoute: ApponboardingOnboardingIndexRoute,
  }

const ApponboardingOnboardingRouteWithChildren =
  ApponboardingOnboardingRoute._addFileChildren(
    ApponboardingOnboardingRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  ApponboardingOnboardingRoute: ApponboardingOnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
